config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  root 'home#index'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update, :index]
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_one :profile, dependent: :destroy
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
      if signed_in?
      @user = User.find(current_user.id)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
      if signed_in?
      @user = User.find(current_user)
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
    @profile = @user.profile
  end

  def update
    @user = current_user
    @profile = current_user.profile
    if @user
      @profile.update(profile_params)
      @profile.save
      flash[:notice] = "Successfully update!"
      redirect_to user_path(@user)
    else
      flash[:noitce] = "Something went wrong :("
      redirect_to :back
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:bio, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def index
    @users = User.all
  end

  def show
    @user = current_user
    @profile = @user.profile
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      @profile = Profile.new
      @profile.user_id = @user.id
      @profile.save
      flash[:notice] = "Success!"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user = current_user
      @user.update(user_params)
      flash[:notice] = "Succesfully updated"
      redirect_to user_path(@user)
    else
      flash[:notice] = "Something went wrong"
      redirect_to dashboard_index_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/dashboard/index.html.erb
<h1>Your Dashboard</h1>
<p>See what's happening in your network</p>

app/views/home/index.html.erb
<h1>Welcome to Coffee Chat</h1>
<p>Peer to peer study support</p>

<%= link_to 'Enter', dashboard_index_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
      <ul class="nav nav-pills">
            <li class="presentation"><%= link_to "Home", dashboard_index_path %></li>
        <% if signed_in? %>
            <li class="presentation"><%= link_to "All Students", users_path %></li>
            <li class="presentation"><%= link_to "Sign Out", session_path, method: :delete %></li>
            <li class="presentation"><%= link_to "My Profile", user_path(current_user) %></li>
          <% else %>
            <li class="presentation"><%= link_to "Sign In", new_session_path %></li>
            <li class="presentation"><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>


  <body>

<% if notice %>
  <p><%= notice %></p>
  <% end %>
<%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

<div>
  <%= form.label :username %>
  <%= form.text_field :username, require: true %>
</div>

<div>
  <%= form.label :first_name %>
  <%= form.text_field :first_name, require: true %>
</div>

<div>
  <%= form.label :last_name %>
  <%= form.text_field :last_name, require: true %>
</div>

  <div>
    <%= form.submit "Update" %>
  </div>

  <% end %>

app/views/users/index.html.erb
<h1>Your fellow users</h1>

 <% @users.each do |user| %>
     <h3><%= user.username %> </h3>

    <div>
      <p><%= user.first_name %></p>
      <p><%= user.last_name %></p>
    </div>
<%= link_to "View User", user_path(user) %>

<% end %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

<div>
  <%= form.label :username %>
  <%= form.text_field :username, require: true %>
</div>

<div>
  <%= form.label :first_name %>
  <%= form.text_field :first_name, require: true %>
</div>

<div>
  <%= form.label :last_name %>
  <%= form.text_field :last_name, require: true %>

</div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email, require: true %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, require: true %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s profile</h1>

<div>
  <p><%= @user.first_name %></p>
  <p><%= @user.last_name %></p>
  <p><%= @user.email %></p>
</div>
  <% if @user = current_user %>
        <% if @user.profile.bio %>
        <p><%= @user.profile.bio %></p>
    <% else %>
        <p>Don't forget to fill out your bio</p>
        <%= form_for @user.profile do |f| %>
            <%= f.text_area :bio, placeholder: "Enter your bio.." %>
            <%= f.submit "Save!" %>
            <% end %>
          <% end %>
    <% end %>
<% if @user = current_user %>
  <%= link_to 'Edit', edit_user_path(@user)%>
<% end %>
<%= link_to 'My Dashboard', dashboard_index_path %>
<%= link_to 'All Users', users_path %>